### ISSUE TITLE
Добавить роль загрузчика.

### ISSUE THREAD

**Issue by alisovenko** [nextgis/installer#37]
Необходимо чтобы nextgisupdater умел запускать наше ПО.

Для чего:
если nextgisupdater вызван из QGIS, то после обновления компонентов он должен уметь запустить QGIS.

Пример реализации:
1. Добавить опцию запуска для nextgisupdater, чтобы можно было при старте указать какой исполняемый файл должен запустить nextgisupdater после обновления компонентов;
2. 
**ИЛИ** добавить опцию запуска для nextgisupdater, чтобы можно было указать с какими параметрами должен запускаться исполняемый файл 
например:
nextgisupdater.exe --updater --launch c:\NextGIS-dev\bin\ngqgis --launch-options "c:\proj.qgs --opt1=qwe "

**ИЛИ** для получения опций запуска исполняемого фала попытаться из некоторого файла 
из временной директории, который будет содержать перечень опций.
Имя файла можно передавать как опция nextgisupdater 

возможны другие варианты?

**Comment by BishopGIS** [comment]
Я за вариант ```nextgisupdater.exe --updater --launch c:\NextGIS-dev\bin\ngqgis --launch-options "c:\proj.qgs --opt1=q"```
Только в плане упрощения я бы сделал в launch все сразу что в execute process должно передаваться если так можно:
```nextgisupdater.exe --updater --launch "c:\NextGIS-dev\bin\ngqgis c:\proj.qgs --opt1=qqq --opt2=www"```

**Comment by BishopGIS** [comment]
@alisovenko перенеси этот тикет в правильный репозиторий, а то о нем никто и не узнает.
Нужно сюда: https://github.com/nextgis/nextgis_installer/issues

**Comment by alisovenko** [comment]
Точно, репозиторий то не тот.
